config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users
  root to: "static#homepage"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :status, :start_date

  after_initialize :set_defaults


  private

    def set_defaults
      self.start_date ||= Date.today - 6.days
    end
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  
  validates_presence_of :date, :rationale, :overtime_request
  validates :overtime_request, numericality: {greater_than: 0.0}

  scope :posts_by, ->(user){ where(user_id: user.id) }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :audit_logs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :phone

  PHONE_REGEX = /\A[0-9]*\Z/

  validates_format_of :phone, with: PHONE_REGEX

  validates :phone, length: { is: 10 }

  def full_name
  	last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin

  def self.admin_types
    ['AdminUser']
  end
  
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :edit, :destroy]

  def index
    @posts = Post.posts_by current_user
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: "Your post was created successfully"
    else
      render :new
    end
  end

  def show
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: "Your post was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: "You post has been deleted"
    end
  end

  private
    def post_params
      params.require(:post).permit(:date, :rationale, :status, :overtime_request)
    end

    def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def status_badge status
    status_span_generator status
  end

  private

    def status_span_generator status
      case status
      when "submitted"
        content_tag(:span, status.titleize, class: 'badge badge-primary')
      when "approved"
        content_tag(:span, status.titleize, class: 'badge badge-success')
      when "rejected"
        content_tag(:span, status.titleize, class: 'badge badge-danger')
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtimeapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/menu' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/alert' %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-8 offset-md-4">
    <%= form_for @post do |f| %>
      <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do | error| %>
          <%= js add_gritter(error, title: "Overtime App Notification", sticky: false, image: :notice)%>
        <% end %>
      <% end %>
      <div class="form-gorup">
        <%= f.label :overtime_request %>
        <%= f.text_field :overtime_request, class: "form-control" %>
      </div>
      <div class="form-gorup">
        <%= f.label :date %>
        <%= f.date_field :date, class: "form-control" %>
      </div>
      <div class="form-gorup">
        <%= f.label :rationale %>
        <%= f.text_field :rationale, class: "form-control" %>
      </div>

      <%= render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser' %>

      <div class="form-gorup">
        <%= f.submit "Save", class: "btn btn-outline-success"%>
      </div>

    <% end %>
  </div>

</div>

app/views/posts/_post.html.erb
<div class="row">

  <div class="col-md-1 col-sm-1 col-2">
    <%= post.id %>
  </div>
  <div class="col-md-1 col-sm-1 col-2">
    <%= post.overtime_request %>
  </div>
  <div class="col-md-2 col-sm-3 col-4">
    <%= post.date %>
  </div>
  <div class="col-md-2 col-sm-2 col-4">
    <%= status_badge post.status %>
  </div>
  <div class="col-md-4 col-sm-5 col-12">
    <p><%= link_to truncate(post.rationale, length: 80), post %></p>
    <small><%= post.user.full_name %></small>
  </div>

  <div class="col-md-2 col-12">
    <%= link_to "Edit", edit_post_path(post), id: "edit_#{post.id}", class: "btn btn-outline-primary float-right" if policy(post).update? %>
    <%= link_to "Delete", post_path(post), method: :delete, id: "delete_post_#{post.id}", data: { confirm: "Are you sure want to delete this post..."}, class: "btn btn-outline-danger float-right" %>
  </div>
</div>
<hr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, "submitted" %>
  <%= f.label :status, "Submitted" %>

  <%= f.radio_button :status, "approved" %>
  <%= f.label :status, "Approved" %>

  <%= f.radio_button :status, "rejected" %>
  <%= f.label :status, "Rejected" %>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="mx-2-auto col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
  <%= render @posts %>

app/views/posts/new.html.erb
<div class="form-post">
  <%= form_for @post do |f| %>
    <%= f.date_field :date %>
    <%= f.text_field :rationale %>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="rationale">
      <%= @post.rationale%>
    </div>
    <div class="card card-body">
      <div class="rationale">
        <h3><span>Overtime Amount Requested:</span><%= @post.overtime_request %></h3>
      </div>
      <div class="rationale">
        <h3><span>Employee:</span><%= @post.user.full_name %></h3>
      </div>
      <div class="rationale">
        <h3><span>Date</span><%= @post.date %></h3>
      </div>
      <div class="rationale">
        <h3><span>Current Stage of Approval</span><%= @post.status %></h3>
      </div>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' if policy(@post).update? %>
    </div>

  </div>
</div>

app/views/shared/_alert.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false)%>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false)%>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false, image: :notice)%>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-faded" style="background-color: #e3f2fd">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Overtime", root_path, class: "navbar-brand #{active?(root_path) } " %>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Post", new_post_path, class: "nav-link" %>
      </li>
    </ul>
    <% if current_user %>
      <span class="navbar-text left-drop">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
          <%# link_to "Admin Dashboard", root_path, class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink", :'data-toggle'=> "dropdown", :"aria-haspopup"=> true, :"aria-expanded"=> false  %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if current_user.try(:type) == 'AdminUser' %>
              <%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Setting", edit_user_registration_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        </ul>
      </span>
    <% end %>
  </div>
</nav>